
# user crendetials for dev 
[auser]
username = "test"
password = "test"

# salt for password hashing 
[salt]
value = "7455e549085dd8e718ce"

[sledpath]
path = "/home/virdis/Source/rust/virdis_me/temp/"
