
# user crendetials for dev 
[user]
username = "test"
password = "test"

[sledpath]
path = "/home/virdis/Source/rust/virdis_me/temp/"

[bodystore]
keyspace = "body"

[metastore]
keyspace = "meta"

[sessionstore]
keyspace = "session"

[userstore]
keyspace = "user"
